### ISSUE TITLE
How do you determine which resource connection to use?

### ISSUE THREAD

**Issue by drewbaumann** [lcharlick/PlexKit#18]
I'm just wondering if there's a good rule of thumb for choosing which resource connection to use.

**Comment by lcharlick** [comment]
The way I do it for Prologue:
- Sort connections by most -> least preferable (e.g. prefer secure, non-relay connections)
- Test each connection (2-3 concurrently) by hitting the [Identity](https://github.com/lcharlick/PlexKit/blob/master/Sources/PlexKit/Requests/Resource/Identity.swift) endpoint
- If a connection succeeds and the response's [machineIdentifier](https://github.com/lcharlick/PlexKit/blob/master/Sources/PlexKit/Requests/Resource/Identity.swift#L31) matches the resource ID we expect, it becomes the "active" connection. If multiple connections succeed, choose the most preferred connection based on the above heuristics
- If a request fails due to a network error at any point, run the above tests again to find a new "active" connection

I also skip testing of remote connections altogether when the device is connected to cellular.

Hope that helps!

**Comment by drewbaumann** [comment]
@lcharlick Thank you! This is helpful. Do you know anything about the local variable and how that plays into preference?

**Comment by drewbaumann** [comment]
> @lcharlick Thank you! This is helpful. Do you know anything about the local variable and how that plays into preference?

Just to answer my own question: If you are on the same local network as your plex server this is preferred.
